### ISSUE TITLE
Consider splitting big org file into org file per chapter

### ISSUE THREAD

**Issue by kozikow** [jkitchin/pycse#18]
I have been reading the book in org format and being to able to read it in org have been amazing experience.

I had to disable a few modes to effectively view the file, since it's that big.

Personally, when my org files grow too big I split them into separate org files.
Some advantages:
-   You can link between org files anyway. Majority of org features can work across multiple org files.
-   Source control gets less confused when you use multiple files. Moving sections around do not generate large diffs in source control. It's less likely to get merge failures.
-   Some Emacs modes do not work well with too big files For example `linum-relative-mode` or `helm-imenu`.

**Comment by kozikow** [comment]
For future reference, personally for me fixing the problem was changing my config to not use `(linum-relative-global-mode 1)` and instead do:

    (require 'linum-relative)
    (add-hook 'prog-mode-hook 'linum-relative-mode)

**Comment by jkitchin** [comment]
I think nlinum might be another solution: https://www.wisdomandwonder.com/article/10066/switch-to-nlinum-immediately
