### ISSUE TITLE
The HTML and PDF versions are out of date and need to be regenerated

### ISSUE THREAD

**Issue by jonsnader** [jkitchin/pycse#25]
The HTML version of the book (http://kitchingroup.cheme.cmu.edu/pycse/pycse.html) and the PDF version (http://kitchingroup.cheme.cmu.edu/pycse/pycse.pdf) are out of date. The discussion of integer versus float division in Section 2.1 does not contain the explanation of the new behavior in Python 3, so the results (e.g. `print (1/3) --> 0.33333333`) do not match the accompanying explanation.

**Comment by jkitchin** [comment]
Thanks for reporting this. I think they are more up to date now.

**Comment by AdityaSavara** [comment]
The html and pdf versions should also contain links to the github. The easiest way is to link to the repository within the overview.

**Comment by jkitchin** [comment]
I finally added links to github here...
