### ISSUE TITLE
args in events of odely

### ISSUE THREAD

**Issue by ghost** [jkitchin/pycse#28]
As already shown, arguments can be defined inside ode functions, yet they are apparently not supported in events definition, so that if the event is defined for some derivatives (for minima or maxima), like in 
def maxima(y, x, args): 
’’’Approaching a maximum, dydx is positive and going to zero. our event function is decreasing’’’
  value = ode(y, x, args)
  direction = -1
  isterminal = False
  return value,  isterminal, direction

the complete code will not be supported, am I wrong?

**Comment by jkitchin** [comment]
You are not wrong. odelay does not support args to events. You are probably better off using the new  scipy.integrate.solve_ivp for this. It also doesn't use args though. It seems that is no longer the preferred way to parameterize ODEs these days.
