### ISSUE TITLE
Errors on using pycse.plotly.myshow

### ISSUE THREAD

**Issue by hatlafax** [jkitchin/pycse#29]
I have just looked the youtube video about scimax and jupyter and tried it in my environment.

With the following example I got two errors:

from pycse.plotly import *
import plotly.express as px
df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", color="species", size='petal_length', hover_data=['petal_width'])
fig.show()

1. File "c:\utils\Python399\lib\encodings\cp1252.py", line 28, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u25c4' in position 276395: character maps to <undefined>

2. File "c:\utils\Python399\lib\site-packages\pycse\plotly.py", line 31, in myshow
    display(FileLink(fhtml, result_html_suffix=""))
TypeError: 'module' object is not callable

I have installed the current version of ploty, i.e, 5.13.0 and I'm using ipython 8.1.0.

In order to get this example running I did make two changes in pycse/plotly.py

For the first error in line 28 the explicit unicode encoding was necessary:
with open(fhtml, "w", encoding="utf-8") as f:

and in line 31 the module display of ipython now provides FileLink so that it changes to:
display.FileLink(fhtml, result_html_suffix="")

With these changes it worked for me as shown in the video.

**Comment by jkitchin** [comment]
Thanks. I made those fixes, and it works better now.
